### ISSUE TITLE
Create page container component with selected state

### ISSUE THREAD

**Issue by jonwalz** [jonfreihofer/coffee-info-sheet#10]
From our last meeting, we talked about creating a component to wrap the sidebar and main content components. 

This container component will need to handle a "selected" state for which link the user clicks on. When the user clicks on a link, we'll need to pass this selected state to the main content component to render the corresponding content.

If we are going to use a class component for the container, we'll need to create a default state. Something like this: 

```
class Container extends React.Component {
  state = {
    selected: ""
  }
...
```

Then we'll need some kind of handler to update this piece of state when the user clicks on a link:

```
handleSelect = (option) => {
  this.setState({ selected: option })
}
```

Once we've captured the selected link, we'll need to pass that option to the content component:
```
<MainContent selected={this.state.selected} />
```

Inside the main content component, we'll need some way to listen to incoming `selected` prop and render the corresponding text. 

I've started on an api for this which we will integrate later but for now, let's just use an object.

Create a new file titled `data.js` or something and we're going to design some data in the shape of what is needed for the `MainContent` component.

Inside the `data.js` file, lets setup the top level of our data to be an object with keys corresponding to the selectable options:

```
// data.js

export default {
  thePant: {},
  theProcess: {},
  thePreparation: {},
  thePresentation: {}
}
```

We'll need to design some content data for each of these page data properties. I'm thinking each will have something like this (for now):

```
thePlant: {
  title: "The Plant",
  content: "This is a paragraph of content"
}
```

Do this for each section to populate the text areas.

It's common and good practice to create a utility function to retrieve the data from within the main content component. For example: 

```
function getPageContent(selectedPage) {
  return data[selectedPage]
}
```

This provides a discrete function that is isolated and testable.

**Comment by jonfreihofer** [comment]
done!
