### ISSUE TITLE
Project needs npm

### ISSUE THREAD

**Issue by jonwalz** [jonfreihofer/coffee-info-sheet#8]
In the world of modern javascript and larger web applications, we no longer link multiple javascript resources in the html file. So we don't have to do this:

```
<script ...
<script ...
<script ...
```

... in your html file.

This is because we now use build systems to compile all the needed javascript code into a single js file. This is often named `bundle.js`

To create this `bundle.js` file we use node and npm. Here a link for more info: 
https://nodejs.org/en/knowledge/getting-started/npm/what-is-npm/

### Add npm:

Npm is basically a command line utility for managing javascript libraries you want to include with your project. It's also a way to publish javascript libraries you've written to share in the npm ecosystem.  

You'll also become familiar with a npm successor called `yarn`. Yarn does a lot of the same things as npm conceptually but handles different versions of the packages in your project a bit better. Read more here: https://waverleysoftware.com/blog/yarn-vs-npm/

With npm we can download all the necessary libraries (such as react, babel, etc) to use in our project, then when we run the build script, it will pull out only the pieces used (functions, classes, variables, etc) and put them in the `bundle.js` file. This is called "tree-shaking".

In order to create a build step, we'll need to add npm to our project. To do this, open a terminal at the root of our project and run: 
`npm init`

This stands for `initialize`. Answer the questions that pop up (you can likely type nothing and hit enter through them all). Don't worry about the `entry point` question. At the end you should now see a `package.json` file in our project. This file helps to maintain consistency across different developers machines. 

We should follow the tutorial for adding parcel to a react project outlined here: 
https://parceljs.org/recipes.html
https://blog.jakoblind.no/react-parcel/

### Add the parcel bundler: 

To install npm packages (think of packages as javascript libraries written by someone else) we use `npm install`. To install parcel bundler, we type `npm install --save-dev parcel-bundler`. The `--save-dev` flag just tells npm that the dependency (the library being installed) isn't used in the built code but only during development. Think of it as a way of telling npm that this library is only a tool for helping you develop and not something that will be added to the bundle. We are using `parcel-bundle` to do the bundling so we don't actually need it in the bundle. Make sense? 

After installing everything, you'll notice a new `node_modules` folder with a bunch of stuff in it.

We need to tell git ignore this folder because it's too large to push to git hub. Anyone with access to this repo will be able to install the needed packages by running `npm install` after cloning this github repo. To tell git to ignore the `node_modules` folder, we create a `.gitignore` file and on the first line put `node_modules`. Git will then know that we never want to commit this folder and changes ever made to it. 

Once you've installed all the needed packages, we just have to rename some things and move our javascript code from out html file into a javascript file.

Here's a checklist of things needed:
- [x] Initialize npm at root of project with `npm init`
- [x] Add all packages/dependencies with `npm install` (Follow the link to the blog provided above)
- [x] Create the babelrc file (In the blog link)
- [x] Create a `.gitignore` file and add `node_modules`
- [x] Move the javascript code we wrote into a new file named `index.js`
- [x] Remove all `<script>` tags from the html file and create one that just imports `index.js`
- [x] Add a script to the `package.json` file to run parcel bundler `"start": "parcel index.html",`

**Comment by jonfreihofer** [comment]
I followed all the steps but i'm getting a `index.js:1 Uncaught SyntaxError: Cannot use import statement outside a module` when i try to preview it. probably did something wrong
